# scripts/ldap/shell_params.py

EXPORT_FORMATS = ["json", "html", "xml", "yaml"]

SCRIPT_PARAMS = {
    # ── enum ──────────────────────────────────────────────────────────────────
    "domain-info": {
        "description": "Enumera información básica del dominio: nombre, SID, nivel funcional, DCs.",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "ldaps", "port", "timeout"],
        "defaults": {"timeout": 5, "ldaps": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    "users": {
        "description": "Enumera usuarios del dominio via LDAP. Soporta filtros por estado y flags.",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "ldaps", "port", "filter_flag", "enabled_only", "timeout"],
        "defaults": {"timeout": 5, "ldaps": False, "enabled_only": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    "groups": {
        "description": "Enumera grupos del dominio. Con privileged_only filtra solo grupos privilegiados.",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "ldaps", "port", "privileged_only", "timeout"],
        "defaults": {"timeout": 5, "ldaps": False, "privileged_only": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    "computers": {
        "description": "Enumera equipos del dominio. Filtra por OS o detecta delegación sin restricciones.",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "ldaps", "port", "os_filter", "undeleg", "timeout"],
        "defaults": {"timeout": 5, "ldaps": False, "undeleg": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    "password-policy": {
        "description": "Extrae la política de contraseñas del dominio (longitud mínima, lockout, etc.).",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "ldaps", "port", "timeout"],
        "defaults": {"timeout": 5, "ldaps": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    "admins": {
        "description": "Enumera miembros de grupos privilegiados (Domain Admins, Enterprise Admins, etc.).",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "ldaps", "port", "timeout"],
        "defaults": {"timeout": 5, "ldaps": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    "dacl-enum": {
        "description": "Enumera ACEs del DACL de un objeto LDAP. Detecta permisos peligrosos.",
        "required": ["target", "domain", "user", "target_dn"],
        "optional": ["password", "hash", "ldaps", "port", "timeout"],
        "defaults": {"timeout": 5, "ldaps": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "set target_dn CN=victim,CN=Users,DC=corp,DC=local",
            "run",
        ],
    },
    "asreproast-targets": {
        "description": "Enumera cuentas con DONT_REQUIRE_PREAUTH (candidatas a AS-REP Roasting).",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "ldaps", "port", "save_list", "timeout"],
        "defaults": {"timeout": 5, "ldaps": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    "kerberoast-targets": {
        "description": "Enumera cuentas con SPN registrado (candidatas a Kerberoasting).",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "ldaps", "port", "save_list", "timeout"],
        "defaults": {"timeout": 5, "ldaps": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    # ── attack ────────────────────────────────────────────────────────────────
    "bloodhound-export": {
        "description": "Exporta datos del dominio en formato BloodHound (JSON) para análisis de rutas de ataque.",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "ldaps", "port", "out_dir", "timeout"],
        "defaults": {"timeout": 5, "ldaps": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    "acl-abuse": {
        "description": "Abusa de ACEs peligrosos: reset de contraseña, add-member, shadow-creds, RBCD.",
        "required": ["target", "domain", "user", "target_obj"],
        "optional": ["password", "hash", "ldaps", "port", "action", "source_user",
                     "new_password", "save_key", "timeout"],
        "defaults": {"timeout": 5, "ldaps": False, "action": "detect"},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "set target_obj CN=victim,CN=Users,DC=corp,DC=local",
            "set action detect",
            "run",
        ],
    },
    # ── exploits ──────────────────────────────────────────────────────────────
    "password-spray-ldap": {
        "description": "Password spray via LDAP (más silencioso que SMB, evita bloqueos con delay).",
        "required": ["target", "domain", "userlist"],
        "optional": ["password", "hash", "ldaps", "port", "delay",
                     "continue_on_lockout", "timeout"],
        "defaults": {"timeout": 5, "ldaps": False, "delay": 0, "continue_on_lockout": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set userlist /ruta/users.txt",
            "set password Summer2024!",
            "set delay 1",
            "run",
        ],
    },
    "ntlm-relay-setup": {
        "description": "Configura y lanza un ataque NTLM relay via LDAP (requiere Responder activo).",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "ldaps", "port", "mode",
                     "relay_target_user", "attacker_ip", "timeout"],
        "defaults": {"timeout": 5, "ldaps": False, "mode": "dump",
                     "relay_target_user": "TARGET_USER"},
        "mutually_exclusive": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "set attacker_ip 10.10.14.5",
            "run",
        ],
    },
}

PARAM_LABELS = {
    "target":             "IP/hostname del DC objetivo",
    "user":               "Usuario",
    "password":           "Contraseña",
    "hash":               "Hash NT (formato NT o LM:NT)",
    "domain":             "Dominio FQDN (ej: CORP.LOCAL)",
    "timeout":            "Timeout de conexión (segundos)",
    "ldaps":              "Usar LDAPS (True/False)",
    "port":               "Puerto LDAP (default: 389 / 636 con ldaps)",
    "userlist":           "Ruta al fichero de usuarios",
    "filter_flag":        "Filtro por flag UAC",
    "enabled_only":       "Solo cuentas habilitadas (True/False)",
    "privileged_only":    "Solo grupos privilegiados (True/False)",
    "os_filter":          "Filtro por sistema operativo",
    "undeleg":            "Solo equipos con delegación sin restricciones (True/False)",
    "target_dn":          "DN del objeto LDAP objetivo",
    "save_list":          "Ruta para guardar la lista resultante",
    "out_dir":            "Directorio de salida para exportaciones",
    "action":             "Acción ACL (detect/reset-password/add-member/write-dacl/shadow-creds/rbcd)",
    "source_user":        "Usuario origen del ACE",
    "target_obj":         "DN o sAMAccountName del objeto objetivo",
    "new_password":       "Nueva contraseña (para reset-password)",
    "save_key":           "Ruta para guardar la clave privada (shadow-creds)",
    "mode":               "Modo relay (add-da/rbcd/dump/shadow-creds)",
    "relay_target_user":  "Usuario objetivo del relay",
    "attacker_ip":        "IP del atacante (para relay)",
    "delay":              "Delay entre intentos de spray (segundos)",
    "continue_on_lockout":"Continuar aunque se detecte lockout (True/False)",
}
