# scripts/kerberos/shell_params.py

EXPORT_FORMATS = ["json", "html", "xml", "yaml"]

SCRIPT_PARAMS = {
    # ── enum ──────────────────────────────────────────────────────────────────
    "user-enum": {
        "description": "Enumera usuarios válidos enviando AS-REQ sin pre-auth al KDC (puerto 88).",
        "required": ["target", "domain", "userlist"],
        "optional": ["timeout"],
        "defaults": {"timeout": 5},
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set userlist /ruta/users.txt",
            "run",
        ],
    },
    "spn-scan": {
        "description": "Enumera cuentas con SPN registrado via LDAP (candidatos a Kerberoasting).",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "timeout"],
        "defaults": {"timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    # ── extraction ────────────────────────────────────────────────────────────
    "asrep-roasting": {
        "description": "AS-REP Roasting: obtiene hashes crackeables de cuentas sin pre-auth requerida.",
        "required": ["target", "domain", "userlist"],
        "optional": ["timeout"],
        "defaults": {"timeout": 5},
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set userlist /ruta/users.txt",
            "run",
        ],
    },
    "kerberoasting": {
        "description": "Kerberoasting: solicita TGS para SPNs y extrae hashes crackeables (hashcat 13100).",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "spn", "timeout"],
        "defaults": {"timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    # ── tickets ───────────────────────────────────────────────────────────────
    "pass-the-ticket": {
        "description": "Carga un ticket .ccache o .kirbi y activa KRB5CCNAME para usar con impacket.",
        "required": [],
        "optional": ["ccache", "kirbi", "timeout"],
        "defaults": {"timeout": 5},
        "at_least_one": [["ccache", "kirbi"]],
        "example": [
            "set ccache /tmp/ticket.ccache",
            "run",
        ],
    },
    "overpass-the-hash": {
        "description": "Convierte un NT hash en un TGT Kerberos (RC4). Genera .ccache para pass-the-ticket.",
        "required": ["target", "domain", "user", "hash"],
        "optional": ["timeout"],
        "defaults": {"timeout": 5},
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user administrator",
            "set hash aad3b435b51404eeaad3b435b51404ee:8846f7eaee8fb117ad06bdd830b7586c",
            "run",
        ],
    },
    "golden-ticket": {
        "description": "Forja un TGT Golden Ticket con el hash krbtgt + domain SID.",
        "required": ["domain", "user", "krbtgt_hash", "domain_sid"],
        "optional": ["user_id", "groups", "timeout"],
        "defaults": {"user_id": 500, "groups": "513,512,520,518,519", "timeout": 5},
        "example": [
            "set domain CORP.LOCAL",
            "set user Administrator",
            "set krbtgt_hash 8846f7eaee8fb117ad06bdd830b7586c",
            "set domain_sid S-1-5-21-1234567890-1234567890-1234567890",
            "run",
        ],
    },
    "silver-ticket": {
        "description": "Forja un Silver Ticket para un servicio específico (SPN) sin krbtgt.",
        "required": ["domain", "user", "service_hash", "domain_sid", "spn"],
        "optional": ["user_id", "timeout"],
        "defaults": {"user_id": 500, "timeout": 5},
        "example": [
            "set domain CORP.LOCAL",
            "set user Administrator",
            "set service_hash 8846f7eaee8fb117ad06bdd830b7586c",
            "set domain_sid S-1-5-21-1234567890-1234567890-1234567890",
            "set spn cifs/DC01.CORP.LOCAL",
            "run",
        ],
    },
    "diamond-ticket": {
        "description": "Diamond Ticket: modifica un TGT real del KDC (más sigiloso que Golden Ticket).",
        "required": ["target", "domain", "user", "krbtgt_hash"],
        "optional": ["password", "hash", "user_id", "groups", "timeout"],
        "defaults": {"user_id": 500, "groups": "513,512,520,518,519", "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "set krbtgt_hash 8846f7eaee8fb117ad06bdd830b7586c",
            "run",
        ],
    },
    "sapphire-ticket": {
        "description": "Sapphire Ticket: S4U2Self con PAC real del usuario (el más sigiloso).",
        "required": ["target", "domain", "user", "krbtgt_hash"],
        "optional": ["password", "hash", "target_user", "timeout"],
        "defaults": {"target_user": "Administrator", "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set krbtgt_hash 8846f7eaee8fb117ad06bdd830b7586c",
            "set target_user Administrator",
            "run",
        ],
    },
    # ── delegation ────────────────────────────────────────────────────────────
    "unconstrained-deleg": {
        "description": "Enumera cuentas con delegación sin restricciones via LDAP.",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "timeout"],
        "defaults": {"timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    "constrained-s4u": {
        "description": "S4U2Self + S4U2Proxy: impersonar usuario a través de delegación restringida.",
        "required": ["target", "domain", "user", "spn"],
        "optional": ["password", "hash", "target_user", "timeout"],
        "defaults": {"target_user": "Administrator", "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user svc-account",
            "set password Pass123!",
            "set spn cifs/DC01.CORP.LOCAL",
            "set target_user Administrator",
            "run",
        ],
    },
    "rbcd": {
        "description": "Resource-Based Constrained Delegation: escribe msDS-AllowedToActOnBehalfOfOtherIdentity.",
        "required": ["target", "domain", "user", "target_computer", "attacker_account"],
        "optional": ["password", "hash", "target_user", "spn", "timeout"],
        "defaults": {"target_user": "Administrator", "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "set target_computer DC01",
            "set attacker_account ATTACKER$",
            "run",
        ],
    },
    # ── credentials ───────────────────────────────────────────────────────────
    "shadow-credentials": {
        "description": "Escribe msDS-KeyCredentialLink para obtener certificado y NT hash sin cambiar contraseña.",
        "required": ["target", "domain", "user", "target_user"],
        "optional": ["password", "hash", "timeout"],
        "defaults": {"timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "set target_user victim",
            "run",
        ],
    },
    "pkinit": {
        "description": "PKINIT: obtiene TGT via certificado y extrae NT hash con User-to-User.",
        "required": ["target", "domain", "user"],
        "optional": ["cert", "pfx", "timeout"],
        "defaults": {"timeout": 5},
        "at_least_one": [["cert", "pfx"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user administrator",
            "set pfx /ruta/cert.pfx",
            "run",
        ],
    },
    "adcs": {
        "description": "Enumera plantillas ADCS vulnerables (ESC1-ESC8) y explota ESC1 via certipy.",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "ca", "template", "alt_name", "timeout"],
        "defaults": {"timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    # ── exploits ──────────────────────────────────────────────────────────────
    "sam-spoofing": {
        "description": "noPac (CVE-2021-42278+42287): escalada a DA creando cuenta de máquina.",
        "required": ["target", "domain", "user"],
        "optional": ["password", "hash", "dc_name", "target_user", "out_dir", "timeout"],
        "defaults": {"target_user": "Administrator", "out_dir": ".", "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "run",
        ],
    },
    "ms14-068": {
        "description": "CVE-2014-6324: forja PAC sin ser DA. Delega a impacket-goldenPac.",
        "required": ["target", "domain", "user", "user_sid"],
        "optional": ["password", "hash", "timeout"],
        "defaults": {"timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "set user_sid S-1-5-21-...-1234",
            "run",
        ],
    },
    "kerber-loss": {
        "description": "CVE-2026-25177: colisión SPN via Unicode para DoS/downgrade/SPN-jacking.",
        "required": ["target", "domain", "user", "spn"],
        "optional": ["password", "hash", "attacker_account", "vector", "timeout"],
        "defaults": {"vector": "dos-colision", "timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "set spn cifs/DC01.CORP.LOCAL",
            "run",
        ],
    },
    "reset-nightmare": {
        "description": "CVE-2026-27912: UPN self-write → kpasswd identity confusion → reset de contraseña.",
        "required": ["target", "domain", "user", "target_user"],
        "optional": ["password", "hash", "new_password", "timeout"],
        "defaults": {"timeout": 5},
        "mutually_exclusive": [["password", "hash"]],
        "at_least_one": [["password", "hash"]],
        "example": [
            "set target 10.10.10.5",
            "set domain CORP.LOCAL",
            "set user iker",
            "set password Pass123!",
            "set target_user victim",
            "run",
        ],
    },
}

PARAM_LABELS = {
    "target":           "IP/hostname del DC objetivo",
    "user":             "Usuario",
    "password":         "Contraseña",
    "hash":             "Hash NT (formato NT o LM:NT)",
    "domain":           "Dominio FQDN (ej: CORP.LOCAL)",
    "timeout":          "Timeout de conexión (segundos)",
    "userlist":         "Ruta al fichero de usuarios",
    "spn":              "SPN objetivo (ej: cifs/DC01.CORP.LOCAL)",
    "ccache":           "Ruta al fichero .ccache",
    "kirbi":            "Ruta al fichero .kirbi",
    "krbtgt_hash":      "Hash NT del krbtgt",
    "service_hash":     "Hash NT de la cuenta de servicio",
    "domain_sid":       "SID del dominio (S-1-5-21-...)",
    "user_id":          "RID del usuario a impersonar (default: 500)",
    "groups":           "RIDs de grupos separados por coma",
    "target_user":      "Usuario objetivo a impersonar",
    "target_computer":  "Nombre del equipo objetivo (sin $)",
    "attacker_account": "Cuenta controlada por el atacante",
    "cert":             "Ruta al certificado .pem",
    "pfx":              "Ruta al certificado .pfx",
    "template":         "Plantilla ADCS a usar",
    "ca":               "CA authority (ej: CORP-CA)",
    "alt_name":         "Nombre alternativo para el certificado",
    "dc_name":          "Nombre del DC (para noPac)",
    "out_dir":          "Directorio de salida para artefactos",
    "user_sid":         "SID del usuario (para ms14-068)",
    "vector":           "Vector de ataque (dos-colision, downgrade, spnjack)",
    "new_password":     "Nueva contraseña a establecer",
}
